apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: odoo-app
  name: odoo-app
spec:
  containers:
  - image: hayquen/odoo-ci:latest
    name: odoo-app
    ports:
    - containerPort: 8069 
    resources: {}
    env:
      - name: DB_NAME
        value: postgres
      - name: DB_HOST
        value: odoo-db.default.svc.cluster.local
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: postgresql-account
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-account
            key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
  - name: docker-secret
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: odoo-app
  name: odoo-app
spec:
  ports:
  - port: 8069
    protocol: TCP
    targetPort: 8069
  selector:
    run: odoo-app
status:
  loadBalancer: {}
